### ISSUE TITLE
Mod crashed on Entry

### ISSUE THREAD

**Issue by rikai** [dmcrider/LastDayToPlant#20]
When starting the game with the latest Stardew Valley and SMAPI versions, the following error is received:

```
Mod crashed on entry and might not work correctly. Technical details:
ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at LastDayToPlant.Crop.FromModFile(String cropFilePath)
   at LastDayToPlant.ModEntry.FindAndLoadCrops(String path)
   at LastDayToPlant.ModEntry.Entry(IModHelper helper)
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in SMAPI\Framework\SCore.cs:line 1802
```

**Comment by dmcrider** [comment]
@rikai Could you provide a list of mods you have installed that add or modify crops? I've fixed the issue, but I'd like to update this mod to be compatible with the conflicting mod before I release the update.
